import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, it, vi } from 'vitest';
import { householdAt, widowedHouseholdAt } from './households';
import { analyze, stubLifeTableFetch } from './harness';
import {
  pdfSurface,
  personPdfSurface,
  personScreenSurface,
  reportSurface,
  screenSurface,
  type Line,
} from './surfaces';

/**
 * Writes every client-facing sentence to `validation/copy/corpus.md`.
 *
 * NOT a test — it asserts nothing. It exists because this project's defects
 * are overwhelmingly in its prose (sixteen copy defects to date, and zero
 * arithmetic ones), and the mechanical checks in `copy.sweep.ts` can only
 * catch mechanical faults: a duplicate sentence, a banned word, a screen and
 * print surface disagreeing. Whether a sentence is CLEAR, correct about
 * Social Security, and safe to put in front of a client is a judgment, and
 * the reviewer making it needs to read what a client reads.
 *
 * So this renders the real surfaces over real analyses — with real
 * interpolated figures, not source literals — and deduplicates. A sentence
 * that only appears for a household with no spousal top-up is in here; a
 * string that exists in a copy module but never reaches a page is not.
 *
 *   npm run copy:corpus
 *
 * Then review it with `/review-copy`. Deliberately a separate step: an LLM
 * judgment is not deterministic, and a blocking test that fails differently
 * on identical input teaches people to ignore the suite.
 */

const COUNT = Number(process.env.CORPUS_COUNT ?? 400);
// `fileURLToPath`, not the URL itself: vitest rewrites `import.meta.url` to
// a non-file scheme in this project's sweep config, and `writeFileSync`
// refuses it.
const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../copy/corpus.md');

beforeAll(() => {
  vi.stubGlobal('fetch', stubLifeTableFetch());
});
afterAll(() => vi.unstubAllGlobals());

describe('client-facing copy corpus', () => {
  it('collects every sentence the generated households can produce', async () => {
    /**
     * The SHAPE of a sentence: the same words with the figures and names
     * taken out.
     *
     * Without this the corpus is thousands of near-identical lines that
     * differ only in a dollar amount, which is the same sentence to anyone
     * reading it for sense — and an unreadable corpus gets skimmed, which
     * defeats the point. Grouping by shape and keeping one REAL example per
     * shape gives a reviewer every distinct sentence the app can say, with
     * genuine figures in it, and a count of how often it arises.
     */
    const shapeOf = (text: string) =>
      text
        .replace(/\$?[\d,]+(?:\.\d+)?%?/g, '#')
        .replace(/\b(?:Alpha|Beta)\b/g, 'NAME');

    const seen = new Map<string, { line: Line; count: number }>();
    const keep = (lines: Line[]) => {
      for (const line of lines) {
        const text = line.text.trim();
        if (text === '') continue;
        const key = line.source + ' :: ' + shapeOf(text);
        const found = seen.get(key);
        if (found === undefined) seen.set(key, { line: { source: line.source, text }, count: 1 });
        else found.count += 1;
      }
    };

    for (let index = 0; index < COUNT; index++) {
      const { household } = householdAt(index);
      const analysis = await analyze(household);
      keep(screenSurface(analysis, 'real'));
      keep(screenSurface(analysis, 'nominal'));
      keep(pdfSurface(analysis));
      keep(reportSurface(analysis));
      for (let person = 0; person < analysis.people.length; person++) {
        keep(personScreenSurface(analysis, person));
        keep(personPdfSurface(analysis, person));
      }
    }

    // Widowed households reach copy no married or single one can: the
    // widow's limit, two claiming dates, a deceased record.
    const widowedCount = Math.round(COUNT / 4);
    for (let index = 0; index < widowedCount; index++) {
      const { household } = widowedHouseholdAt(index);
      const analysis = await analyze(household);
      keep(screenSurface(analysis, 'real'));
      keep(pdfSurface(analysis));
      keep(reportSurface(analysis));
      keep(personScreenSurface(analysis, 0));
      keep(personPdfSurface(analysis, 0));
    }

    const bySource = new Map<string, { text: string; count: number }[]>();
    for (const entry of seen.values()) {
      const list = bySource.get(entry.line.source) ?? [];
      list.push({ text: entry.line.text, count: entry.count });
      bySource.set(entry.line.source, list);
    }

    const parts: string[] = [
      '# Client-facing copy corpus',
      '',
      'Generated by `npm run copy:corpus` from ' + COUNT + ' generated households',
      '(plus ' + widowedCount + ' widowed). Do not edit by hand — regenerate.',
      '',
      seen.size + ' distinct sentence shapes across ' + bySource.size + ' sources.',
      '',
      'Each heading is the component and function that renders the lines beneath it,',
      'so a finding names a file to open. Sentences differing only in their figures',
      'are collapsed to one entry showing a REAL example; the count in brackets is',
      'how many households produced that shape, which is a rough measure of how many',
      'readers would see it.',
      '',
    ];
    for (const source of [...bySource.keys()].sort()) {
      const lines = bySource.get(source)!.sort((a, b) => a.text.localeCompare(b.text));
      parts.push('## ' + source, '');
      for (const entry of lines) parts.push('- [x' + entry.count + '] ' + entry.text);
      parts.push('');
    }

    writeFileSync(OUT, parts.join('\n') + '\n');
    console.log('Wrote ' + seen.size + ' sentence shapes from ' + bySource.size + ' sources');
  }, 600_000);
});
