/**
 * Typed loader for the golden calculation fixtures.
 *
 * scenarios.json is the single source of truth for expected Social Security
 * values, hand-derived from SSA's published reduction/credit rules (see the
 * "conventions" field). It drives BOTH the Vitest engine suite
 * (validation/engine/golden.test.ts) and the Playwright UI suite
 * (validation/e2e/golden-scenarios.spec.ts) so expected values are never
 * duplicated.
 */
import { readFileSync } from 'node:fs';

export interface ScenarioPerson {
  name?: string;
  birthYear: number;
  birthMonth: number;
  gender: 'female' | 'male';
  piaMonthly: number;
  lifeExpectancy: number;
}

export interface ScenarioInputs {
  /** ISO date the scenario is evaluated as-of, e.g. "2026-01-15". Pinning
   * this makes fixtures deterministic and stops cohorts ageing out of the
   * mortality-weighted optimizer as real time passes. */
  asOf: string;
  status: 'single' | 'married';
  /** One entry for 'single', two for 'married'. Index 0 is the person the
   * legacy fixtures called "worker"; index 1 (when present) is "spouse". */
  people: ScenarioPerson[];
  annualCola: number;
  discountRate: number;
}

export interface ExpectedBreakEven {
  earlierAge: number;
  laterAge: number;
  breakEvenAge: number;
}

export interface ScenarioExpected {
  /** Indexed like inputs.people. */
  fraByPerson: { years: number; months: number; label: string }[];
  monthlyByClaimAgeByPerson: Record<string, number>[];
  percentOfPiaByClaimAgeByPerson: Record<string, number>[];
  breakEvensByPerson: ExpectedBreakEven[][];
  /**
   * The unreduced spousal entitlement: max(0, higherPIA/2 - lowerPIA). A
   * dateless reference figure, never what anyone is actually paid.
   * Independently derivable without the engine.
   */
  spousalTopUpAtFra: number | null;
  /**
   * The top-up the lower earner actually receives under the optimizer's
   * recommended strategy, after the SSA early-filing reduction measured from
   * the date the benefit *begins* (see startsAtSpouseAge) against their own
   * FRA. Depends on the optimizer's output, so — unlike spousalTopUpAtFra —
   * this cannot be derived independently; it is hand-derived per scenario
   * (see each scenario's description) and cross-checked against the engine,
   * not generated by gen-fixtures.mjs.
   */
  spousalTopUpAtFilingAge: number | null;
  /**
   * The lower earner's age when the spousal benefit actually begins, as the
   * displayed label (e.g. "68 years, 3 months", or just "67" on a whole
   * year). A spousal benefit is payable only once the higher earner has
   * filed, so this is their age at max(higher filing date, own filing date)
   * — not their own filing age. null where no top-up is payable.
   */
  startsAtSpouseAge: string | null;
  /** Indexed like inputs.people. */
  optimalAgeRangeByPerson: [number, number][];
  invariants: string[];
}

/**
 * 'full' runs the complete analyzeHousehold pipeline (optimizer, mortality
 * tables) and the Playwright UI suite — only valid while every person in the
 * household is under 70 as of `asOf`, because the optimizer needs at least
 * one prospective filing age. 'factorsOnly' validates the deterministic
 * benefit-factor math directly and never ages out — used for older cohorts
 * kept for FRA-schedule coverage.
 */
export type ScenarioMode = 'full' | 'factorsOnly';

export interface GoldenScenario {
  id: string;
  description: string;
  mode: ScenarioMode;
  inputs: ScenarioInputs;
  expected: ScenarioExpected;
  e2e: { assertTable: boolean; assertSummaryCards: boolean };
}

/** Schema version 2: the people[]/asOf household shape (see ScenarioInputs).
 * Version 1 was the flat worker/spouse shape consumed by the legacy
 * analyzeClaiming pipeline, migrated away from in Task 21. */
const CURRENT_VERSION = 2;

export interface GoldenFixtures {
  version: number;
  conventions: string;
  tolerances: {
    monthlyUsd: number;
    percentOfPia: number;
    breakEvenYears: number;
    crosscheckUsd: number;
  };
  scenarios: GoldenScenario[];
}

export function loadScenarios(): GoldenFixtures {
  const url = new URL('./scenarios.json', import.meta.url);
  const fixtures = JSON.parse(readFileSync(url, 'utf8')) as GoldenFixtures;
  if (fixtures.version !== CURRENT_VERSION) {
    throw new Error(
      `scenarios.json is version ${fixtures.version}, but the loader expects ` +
        `version ${CURRENT_VERSION}. Migrate the fixtures or update CURRENT_VERSION.`,
    );
  }
  return fixtures;
}
