/**
 * Typed loader for the golden calculation fixtures.
 *
 * scenarios.json is the single source of truth for expected Social Security
 * values, hand-derived from SSA's published reduction/credit rules (see the
 * "conventions" field). It drives BOTH the Vitest engine suite
 * (validation/engine/golden.test.ts) and the Playwright UI suite
 * (validation/e2e/golden-scenarios.spec.ts) so expected values are never
 * duplicated.
 */
import { readFileSync } from 'node:fs';
import type { AlreadyClaimed } from '../../src/lib/widowed';
import type { Deceased } from '../../src/lib/deceased';

export interface ScenarioPerson {
  name?: string;
  birthYear: number;
  birthMonth: number;
  gender: 'female' | 'male';
  piaMonthly: number;
  lifeExpectancy: number;
}

export interface ScenarioInputs {
  /** ISO date the scenario is evaluated as-of, e.g. "2026-01-15". Pinning
   * this makes fixtures deterministic and stops cohorts ageing out of the
   * mortality-weighted optimizer as real time passes. */
  asOf: string;
  status: 'single' | 'married' | 'widowed';
  /** One entry for 'single' and 'widowed' (the survivor), two for 'married'.
   * Index 0 is the person the legacy fixtures called "worker"; index 1 (when
   * present) is "spouse". */
  people: ScenarioPerson[];
  annualCola: number;
  discountRate: number;
  /** Only present when status is 'widowed' — the deceased spouse's record. */
  deceased?: Deceased;
  /** Only present when status is 'widowed'. */
  alreadyClaimed?: AlreadyClaimed;
}

export interface ExpectedBreakEven {
  earlierAge: number;
  laterAge: number;
  breakEvenAge: number;
}

export interface ScenarioExpected {
  /** Indexed like inputs.people. */
  fraByPerson: { years: number; months: number; label: string }[];
  monthlyByClaimAgeByPerson: Record<string, number>[];
  percentOfPiaByClaimAgeByPerson: Record<string, number>[];
  breakEvensByPerson: ExpectedBreakEven[][];
  /**
   * The unreduced spousal entitlement: max(0, higherPIA/2 - lowerPIA). A
   * dateless reference figure, never what anyone is actually paid.
   * Independently derivable without the engine.
   */
  spousalTopUpAtFra: number | null;
  /**
   * The top-up the lower earner actually receives under the optimizer's
   * recommended strategy, after the SSA early-filing reduction measured from
   * the date the benefit *begins* (see startsAtSpouseAge) against their own
   * FRA. Depends on the optimizer's output, so — unlike spousalTopUpAtFra —
   * this cannot be derived independently; it is hand-derived per scenario
   * (see each scenario's description) and cross-checked against the engine,
   * not generated by gen-fixtures.mjs.
   */
  spousalTopUpAtFilingAge: number | null;
  /**
   * The lower earner's age when the spousal benefit actually begins, as the
   * displayed label (e.g. "68 years, 3 months", or just "67" on a whole
   * year). A spousal benefit is payable only once the higher earner has
   * filed, so this is their age at max(higher filing date, own filing date)
   * — not their own filing age. null where no top-up is payable.
   */
  startsAtSpouseAge: string | null;
  /** Indexed like inputs.people. */
  optimalAgeRangeByPerson: [number, number][];
  /**
   * The filing age the optimizer actually recommends for each person, indexed
   * like inputs.people. Null for 'factorsOnly' scenarios, which never run the
   * optimizer.
   *
   * **Engine-recorded, not hand-derived.** Unlike every other expected value
   * in this file, these are optimizer outputs over empirical SSA/CDC life
   * tables — there is no published closed form to derive them from, which is
   * precisely why `optimalAgeRangeByPerson` was left as the permissive
   * `[62, 70]` window. But `[62, 70]` is the whole legal range, so running the
   * golden suite could not detect a moved filing age at all, and "every
   * recommended filing age is unchanged" was an unguarded claim. Recording
   * them makes the suite a regression detector for the one invariant the
   * benefit-periods rebase turns on. If one of these ever changes, do NOT
   * re-record it to make the suite green: find out what moved the optimizer.
   */
  recommendedFilingAgeByPerson: { years: number; months: number }[] | null;
  /**
   * The survivor's age at the best survivor-claim month, and the lifetime
   * gain over what the app displays — null where no alternative applies
   * (single claimant, a tie in plan-to months, the engine's unmodelled
   * survivor direction already disclosed via `survivorGap`, or the survivor
   * already claims early enough that no month improves on the baseline).
   *
   * **Engine-recorded, not hand-derived — the same class as
   * `recommendedFilingAgeByPerson`, not the class `spousalTopUpAtFilingAge`
   * belongs to.** `survivorClaimAlternative` (`src/lib/survivorClaim.ts`)
   * searches over the optimizer's own chosen filing ages, which have no
   * published closed form, so this cannot be independently derived and is
   * preserved per scenario id by gen-fixtures.mjs exactly as
   * `recommendedFilingAgeByPerson` is. Never re-record one of these to make
   * the golden suite pass: a moved claim age or gain is the regression the
   * field exists to catch.
   */
  survivorClaim: { claimAge: string; gain: number } | null;
  /**
   * WIDOWED-ONLY. The survivor's own filing age under the household's optimal
   * strategy, as the displayed label (e.g. "62 years, 1 month", or a bare
   * "70" on a whole year) — `result.optimal.filingAges[0].label` for a
   * widowed household. Null for every single and married scenario in this
   * file, where the household has no widowed-shaped "optimal" row to read it
   * from.
   *
   * **Engine-recorded, not hand-derived — same class as
   * `recommendedFilingAgeByPerson`.** `bestWidowedOutcome` (src/lib/widowed.ts)
   * exhaustively searches the survivor's own filing date jointly with the
   * survivor-claim date, so there is no published closed form to re-derive it
   * from; gen-fixtures.mjs preserves it per scenario id and throws rather than
   * fabricate a value for a new widowed scenario. Never re-record one to make
   * the golden suite pass — a moved filing age is the regression it exists to
   * catch.
   */
  recommendedOwnFilingAge: string | null;
  /**
   * WIDOWED-ONLY. The survivor's age at the best survivor-claim month under
   * the household's optimal strategy — `result.optimal.survivorClaimDate.age`
   * for a widowed household. Null for every single and married scenario.
   *
   * Do not confuse with `survivorClaim` above: that field is the Phase 3A
   * MARRIED-household survivor-claim alternative (`SurvivorClaimAlternative`,
   * with `claimAge`/`gain`), which stays structurally null for a widowed
   * household (see `HouseholdAnalysis.survivorClaim`'s own docstring) because
   * a widow(er)'s survivor-claim date is not an "alternative" to search for —
   * it is one half of the widowed optimum itself, which is what this field
   * records instead.
   *
   * **Engine-recorded, not hand-derived — same class as
   * `recommendedOwnFilingAge` immediately above.** Preserved per scenario id
   * by gen-fixtures.mjs for the same reason: `bestWidowedOutcome`'s search has
   * no published closed form.
   */
  recommendedSurvivorClaimAge: string | null;
  /**
   * WIDOWED-ONLY. The household's optimal strategy's straight-sum lifetime
   * total — `result.optimal.lifetimeTotal` — undiscounted, today's dollars,
   * from the month after the death through the survivor's plan-to age. NOT
   * comparable with `expectedNpv`, which is what every single and married
   * scenario in this file is scored by instead; null for all of them.
   *
   * **Engine-recorded, not hand-derived — same class as the two widowed
   * fields above.** The search that produces it has no published closed form,
   * so gen-fixtures.mjs preserves it per scenario id rather than deriving it.
   */
  lifetimeTotal: number | null;
  invariants: string[];
}

/**
 * 'full' runs the complete analyzeHousehold pipeline (optimizer, mortality
 * tables) and the Playwright UI suite — only valid while every person in the
 * household is under 70 as of `asOf`, because the optimizer needs at least
 * one prospective filing age. 'factorsOnly' validates the deterministic
 * benefit-factor math directly and never ages out — used for older cohorts
 * kept for FRA-schedule coverage.
 */
export type ScenarioMode = 'full' | 'factorsOnly';

export interface GoldenScenario {
  id: string;
  description: string;
  mode: ScenarioMode;
  inputs: ScenarioInputs;
  expected: ScenarioExpected;
  e2e: { assertTable: boolean; assertSummaryCards: boolean };
}

/** Schema version 2: the people[]/asOf household shape (see ScenarioInputs).
 * Version 1 was the flat worker/spouse shape consumed by the legacy
 * analyzeClaiming pipeline, migrated away from in Task 21. */
const CURRENT_VERSION = 2;

export interface GoldenFixtures {
  version: number;
  conventions: string;
  tolerances: {
    monthlyUsd: number;
    percentOfPia: number;
    breakEvenYears: number;
    crosscheckUsd: number;
  };
  scenarios: GoldenScenario[];
}

export function loadScenarios(): GoldenFixtures {
  const url = new URL('./scenarios.json', import.meta.url);
  const fixtures = JSON.parse(readFileSync(url, 'utf8')) as GoldenFixtures;
  if (fixtures.version !== CURRENT_VERSION) {
    throw new Error(
      `scenarios.json is version ${fixtures.version}, but the loader expects ` +
        `version ${CURRENT_VERSION}. Migrate the fixtures or update CURRENT_VERSION.`,
    );
  }
  return fixtures;
}
